export const COLORS = {
    PRIMARY_BACKGROUND_COLOR: '#F9F9F9',
    SECONDARY_BACKGROUND_COLOR: '#EFEFEF',
    PRIMARY_TEXT_COLOR: '#505050',
    SECONDARY_TEXT_COLOR: '#868686',
    LIGHT_TEXT_COLOR: '#ABABAB',
    HINT_TEXT_COLOR: '#D5D5D5',
    INPUT_BORDER_COLOR: '#C7C7C7',
    SUBMIT_BUTTON_BACKGROUND_COLOR: '#46A9DD',
    SUBMIT_BUTTON_ACTIVE_BACKGROUND_COLOR: '#0a94d8'
}
